name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.org'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin/1.13, ecl/24.5.10]
        os: [ubuntu-latest, macos-latest]
        exclude:
          - os: macos-latest
            lisp: ccl-bin/1.13
          - os: macos-latest
            lisp: ecl/24.5.10
    env:
      LISP: ${{ matrix.lisp }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Ultralisp
        run: ros -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'
      - name: Install Rove
        run: ros install parachute
      - name: Run tests
        run: ros run -e '(quicklisp:quickload :cl-binary-store) (quicklisp:quickload :cl-binary-store/tests) (defparameter *exit-on-test-failures* t) (parachute:test :cl-binary-store-tests)'
